language: go
go:
  - 1.6.4
  - 1.7.4
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
after_success:
  test -n "$TRAVIS_TAG" && go get github.com/goreleaser/releaser && releaser
